FROM python:3.8-bullseye

WORKDIR /api

ADD ./requirements.txt ./

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && python3 -m pip install --upgrade setuptools \
    && pip install -r requirements.txt

ADD . .

CMD python manage.py migrate; daphne -b 0.0.0.0 -p 8000 crypmo.asgi:application 