# Generated by Django 4.0 on 2022-02-03 23:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('ticker', models.CharField(max_length=5, unique=True)),
                ('contract', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='exchange.blockchain')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default=None, max_length=2)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='accounts.account')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='exchange.coin')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4)),
                ('type', models.CharField(choices=[('L', 'Limit'), ('M', 'Market')], default=None, max_length=2)),
                ('position', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default=None, max_length=2)),
                ('amount', models.FloatField()),
                ('filled', models.FloatField(default=0)),
                ('price', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.account')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.coin')),
            ],
        ),
        migrations.CreateModel(
            name='FiatBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiat', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='CoinBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='accounts.account')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.coin')),
            ],
        ),
    ]
