# Generated by Django 4.0 on 2022-02-23 12:30

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(django.db.models.expressions.F('coin'), django.db.models.functions.datetime.TruncDate('created_at'), django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True), name='trade_idx'),
        ),
    ]
