# Generated by Django 4.0 on 2022-03-12 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_remove_trade_trade_idx_trade_trade_date_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('m1', 'M1'), ('h1', 'H1'), ('h4', 'H4'), ('d1', 'D1')], max_length=3)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='exchange.coin')),
            ],
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(django.db.models.expressions.F('coin'), django.db.models.expressions.F('interval'), django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True), name='candles_idx'),
        ),
    ]
