# Generated by Django 4.0 on 2022-03-13 21:24

from django.db import migrations, models
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_candle_candle_candles_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candle',
            name='candles_idx',
        ),
        migrations.AddField(
            model_name='candle',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(django.db.models.expressions.F('coin'), django.db.models.expressions.F('interval'), django.db.models.expressions.OrderBy(django.db.models.expressions.F('time'), descending=True), name='candles_idx'),
        ),
    ]
