# Generated by Django 4.0 on 2022-03-22 22:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_remove_candle_candles_idx_candle_time_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('coin'), django.db.models.expressions.F('interval'), django.db.models.expressions.F('time'), name='candles_unique'),
        ),
    ]
