# Generated by Django 4.0 on 2022-03-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_candle_candles_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candle',
            name='candles_unique',
        ),
    ]
